name: CI/CD para desenvolvimento (develop)

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
    push:
        branches: [ develop ]

jobs:
    Deploy-Preview:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v3

            - name: Install Vercel CLI
              run: npm install --global vercel

            - name: Pull Vercel Environment Information
              run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

            - name: Build Project Artifacts
              run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

            - name: Deploy Project Artifacts
              id: deploy
              run: |
                DEPLOY_URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} --confirm)
                echo "VERCEL_PREVIEW_URL=$DEPLOY_URL" >> $GITHUB_ENV

            - name: Post Vercel preview URL to PR comment
              if: github.event_name == 'pull_request'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  PREVIEW_URL: ${{ env.VERCEL_PREVIEW_URL }}
              run: |
                  # Obter número do PR
                  PR_NUMBER=$(echo ${{ github.event.pull_request.number }})

                  # Comentar no PR com a URL de preview
                  curl -s -X POST \
                    -H "Authorization: token $GITHUB_TOKEN" \
                    -H "Content-Type: application/json" \
                    -d "{\"body\": \"**Preview URL:** $PREVIEW_URL\"}" \
                    https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/issues/$PR_NUMBER/comments