name: CI/CD para desenvolvimento (develop)

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ develop ]

jobs:
  build-preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build development bundle
        run: npm run build

      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Generate Vercel preview URL
        id: generate-preview-url
        run: |
          # Gerar URL de preview para a branch atual
          VERCEL_URL=$(vercel deploy --prebuilt --token $VERCEL_TOKEN)

          # Salvar URL de preview como variável de ambiente
          echo "VERCEL_PREVIEW_URL=$VERCEL_URL" >> $GITHUB_ENV

      - name: Post Vercel preview URL to PR comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PREVIEW_URL: ${{ env.VERCEL_PREVIEW_URL }}
        run: |
          # Obter número do PR
          PR_NUMBER=$(echo ${{ github.event.ref }} | awk -F/ '{print $3}')

          # Comentar no PR com a URL de preview
          curl -s -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "{\"body\": \"**Preview URL:** $PREVIEW_URL\"}" \
            https://api.github.com/repos/${{ github.repository_owner }}/${{ github.repository }}/issues/$PR_NUMBER/comments
