name: CI/CD para produção (main)

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20."

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build production bundle
        run: npm run build

      - name: Deploy to Vercel (production)
        env:
          VERCEL_GIT_TOKEN: ${{ secrets.VERCEL_GIT_TOKEN }}
        run: |
          # Instalar o CLI da Vercel
          npm install -g vercel

          # Entrar na conta da Vercel
          vercel login ${{ secrets.VERCEL_GIT_TOKEN }}

          # Implantar o diretório de compilação para a produção
          vercel deploy --prod .
