name: CI/CD para produção (main)

env:
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build production bundle
        run: npm run build

      - name: Deploy to Vercel (production)
        run: |
          # Instalar o CLI da Vercel
          npm install -g vercel

          # Implantar o diretório de compilação para a produção
          vercel deploy --prod --token $VERCEL_TOKEN
